/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kalmankostenszky' at '2016.10.17. 22:40' with Gradle 3.1
 *
 * @author kalmankostenszky, @date 2016.10.17. 22:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
