drop table users;
drop table customers;
drop table cases;
drop table case_types;
drop table events;
drop table event_types;
drop table agreements;
drop table payment_types;
drop table documents;