DROP TABLE esemeny CASCADE;
DROP TABLE tevekenyseg CASCADE;
DROP TABLE eroforras CASCADE;
DROP TABLE felhasznalas CASCADE;
DROP TABLE szemely CASCADE;
DROP TABLE reszleg CASCADE;
DROP TABLE halo CASCADE;

