DROP TABLE artistsong;
DROP TABLE albumsong;
DROP TABLE trackliststreamingurl;
DROP TABLE streamingurl;
DROP TABLE tracklist;
DROP TABLE song;
DROP TABLE customer;
DROP TABLE album;
DROP TABLE artist;
