TRUNCATE TABLE albumsong CASCADE;
TRUNCATE TABLE trackliststreamingurl CASCADE;
TRUNCATE TABLE streamingurl CASCADE;
TRUNCATE TABLE tracklist CASCADE;
TRUNCATE TABLE song CASCADE;
TRUNCATE TABLE customer CASCADE;
TRUNCATE TABLE album CASCADE;
TRUNCATE TABLE artist CASCADE;
