CREATE TABLE CBMS_USER (
	user_id SERIAL NOT NULL,
	user_name CHARACTER VARYING(20) NOT NULL,
	user_pw CHARACTER VARYING(20) NOT NULL,
	user_email CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT PK_USER_ID PRIMARY KEY (user_id)
);

CREATE TABLE CBMS_BOOKMARK (
	bookmark_id SERIAL NOT NULL,
	bookmark_title CHARACTER VARYING(100) NOT NULL,
	bookmark_url CHARACTER VARYING(500) NOT NULL,
	bookmark_description TEXT,
	bookmark_preview CHARACTER VARYING(500) NOT NULL,
	bookmark_owner INTEGER NOT NULL,
	CONSTRAINT PK_BOOKMARK_ID PRIMARY KEY (bookmark_id),
	CONSTRAINT FK_bookmark_user FOREIGN KEY (bookmark_owner) REFERENCES CBMS_USER (user_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE CBMS_SHARE (
	share_id SERIAL NOT NULL,
	share_date DATE NOT NULL,
	share_bookmark INTEGER NOT NULL,
	CONSTRAINT PK_SHARE_ID PRIMARY KEY (share_id),
	CONSTRAINT FK_SHARE_BOOKMARK FOREIGN KEY (share_bookmark) REFERENCES CBMS_BOOKMARK (bookmark_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE CBMS_KEYWORD (
	keyword_id SERIAL NOT NULL,
	keyword CHARACTER VARYING(20) NOT NULL,
	CONSTRAINT PK_KW_ID PRIMARY KEY (keyword_id)
);

CREATE TABLE CBMS_BM_KW_CONNECTION (
    connection_id SERIAL NOT NULL,
	bookmark INTEGER NOT NULL,
	keyword INTEGER NOT NULL,
	CONSTRAINT PK_BMKWCON_ID PRIMARY KEY (connection_id),
	CONSTRAINT FK_BOOKMARK FOREIGN KEY (bookmark) REFERENCES CBMS_BOOKMARK (bookmark_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_KEYWORD FOREIGN KEY (keyword) REFERENCES CBMS_KEYWORD (keyword_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE CBMS_SHARE_KW_CONNECTION (
    connection_id SERIAL NOT NULL,
	cbms_share INTEGER NOT NULL,
	keyword INTEGER NOT NULL,
	CONSTRAINT PK_SHKWCON_ID PRIMARY KEY (connection_id),
	CONSTRAINT FK_SHARE FOREIGN KEY (cbms_share) REFERENCES CBMS_SHARE (share_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_KEYWORD FOREIGN KEY (keyword) REFERENCES CBMS_KEYWORD (keyword_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE CBMS_USER OWNER TO centbmstorage_user;
ALTER TABLE CBMS_BOOKMARK OWNER TO centbmstorage_user;
ALTER TABLE CBMS_SHARE OWNER TO centbmstorage_user;
ALTER TABLE CBMS_KEYWORD OWNER TO centbmstorage_user;
ALTER TABLE CBMS_BM_KW_CONNECTION OWNER TO centbmstorage_user;
ALTER TABLE CBMS_SHARE_KW_CONNECTION OWNER TO centbmstorage_user;

CREATE UNIQUE INDEX UI_KEYWORD_KW ON CBMS_KEYWORD (keyword);